### PR TITLE
Added login support

### PR DESCRIPTION
**Pull request by mukkachaitanya**
- Added admin login support (`/admin`, need to add further admin pages) 
- Added a copy of main.css

### CODE REVIEW

**Comment by 0xRampey** [comment]
@mukkachaitanya Why did you add a copy of main.css?

**Comment by mukkachaitanya** [comment]
It was requested by @SebastinSanty  ! 
Anyway I should have made it in a different commit.

**Comment by 0xRampey** [comment]
@mukkachaitanya We can always remove that later. Nice design btw. So right now you hardcoded the default admin credentials right? Is there a database sitting anywhere?

**Comment by mukkachaitanya** [comment]
Well sort of. That's where i thought maybe I need a different logic. By the way the default credentials are admin and admin. 
Yup see `db.js`, where I made chnages to add a new users database. Also see `config.js`, where I write the admin credentials.

**Comment by 0xRampey** [comment]
Oh that's good. I'll merge it then.

**Pull request merged**
